config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :lists do
    resources :collaborations, only: [:index, :create]
  end
  resources :collaborations, only: [:destroy]

  root 'main#index'
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user

  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user

  has_many :collaborations

  has_many(
    :collaborators,
    through: :collaborations,
    source: :user,
    class_name: User.name,
    foreign_key: 'user_id',
    dependent: :destroy
  )

  validates(
    :user,
    presence: true
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many(
    :lists,
    dependent: :destroy
  )

  has_many :collaborations

  has_many(
    :shared_lists,
    through: :collaborations,
    source: :list,
    class_name: List.name,
    foreign_key: 'list_id',
    dependent: :destroy
  )

  def all_lists
    lists.to_ary.concat(shared_lists.to_ary)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  include Concerns::UserAuthorizable

  respond_to :js

  before_action :authenticate_user!
  before_action :authorize_own_list_collaborations, only: [:index, :create]
  before_action :authorize_own_collaborations, only: :destroy

  def index
    find_list
    render_index
  end

  def create
    find_list
    user = User.find_by_email collaboration_params[:user]
    alert = check_for_create_error user
    return render_alert(alert) unless alert.nil?
    @list.collaborations.build(user: user).save!
    render_index
  end

  def destroy
    collaboration = Collaboration.find_by_id(params[:id])
    return head :bad_request if collaboration.nil?
    @list = collaboration.list
    collaboration.destroy unless collaboration.nil?
    render_index
  end

  private

  def find_list
    @list = List.find_by_id(params[:list_id])
  end

  def check_for_create_error(user)
    return I18n.t('controllers.collaboration.user_not_found') if user.nil?
    return I18n.t('controllers.collaboration.user_already_sharing') if @list.collaborators.include?(user)
    return I18n.t('controllers.collaboration.user_is_owner') if @list.user == user
  end

  def render_alert(alert)
    render partial: 'alert', locals: { alert: alert }
  end

  def render_index
    @collaborations = @list.collaborations
    @collaboration = Collaboration.new
    render 'index'
  end

  def collaboration_params
    params.require(:collaboration).permit(:user, :id)
  end
end

app/controllers/concerns/user_authorizable.rb
module Concerns
  module UserAuthorizable
    extend ActiveSupport::Concern

    included do
      # restricts a user to accessing only their data
      def authorize_user!
        return if !@user.nil? && @user == current_user
        redirect_to root_path, alert: I18n.t('controllers.user.unauthorized')
      end

      # restrics a user to accessing only their own lists
      def authorize_own_lists
        authorize_lists current_user.lists
      end

      # restrics a user to accessing their own lists
      # or lists that have been shared with them
      def authorize_own_or_shared_lists
        authorize_lists current_user.all_lists
      end

      def authorize_lists(lists)
        return if lists.map(&:id).include? params[:id].to_i
        redirect_to root_path, alert: I18n.t('controllers.user.unauthorized')
      end

      # restricts a user to accessing only collaborations belonging to their lists
      def authorize_own_list_collaborations
        render_alert(I18n.t('controllers.user.unauthorized')) unless users_list?(params[:list_id])
      end

      # restricts a user to accessing only their own collaborations
      # or collaborations belonging to their list
      def authorize_own_collaborations
        render_alert(I18n.t('controllers.user.unauthorized')) unless users_collaboration?(params[:id]) || users_list_collaboration?(params[:id])
      end

      def users_list?(list_id)
        current_user.lists.map(&:id).include? list_id.to_i
      end

      def users_collaboration?(collaboration_id)
        current_user.collaborations.map(&:id).include? collaboration_id.to_i
      end

      def users_list_collaboration?(collaboration_id)
        current_user.lists.map(&:collaborations).flatten.map(&:id).include? collaboration_id.to_i
      end
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  include Concerns::UserAuthorizable

  respond_to :html, :js

  before_action do
    authenticate_user!
  end
  before_action :authorize_own_or_shared_lists, only: [:show, :edit, :update]
  before_action :authorize_own_lists, only: :destroy
  before_action :find_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = current_user.all_lists.sort! { |x, y| y.updated_at <=> x.updated_at }
  end

  def new
    @list = current_user.lists.build
  end

  def create
    @list = current_user.lists.build(list_params)
    @list.save!
  end

  def update
    @list.update_attributes(list_params)
  end

  def destroy
    flash[:notice] = I18n.t('controllers.list.list_deleted') if @list.destroy
    redirect_to root_path
  end

  private

  def find_list
    @list = List.find_by_id(params[:id])
  end

  def list_params
    params.require(:list).permit(:title, :body)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    return unless user_signed_in?
    redirect_to lists_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Concerns::UserAuthorizable

  before_action do
    authenticate_user!
    @user = User.find(params[:id])
    authorize_user!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # intercept devise errors and display them as flash messages
  def devise_error_messages!
    return if resource.errors.empty?
    str = ''
    resource.errors.full_messages.each do |msg|
      str += "#{msg}. "
    end
    flash.now[:devise_error] = str
    nil
  end
end

app/views/collaborations/_alert.js.erb
$('#form-alert-container').append($("<div data-alert class='alert-box alert'><%= alert %><a href='#' class='close'>&times;</a></div>"));
$(document).foundation();  // reapply foundation after adding content to modal

app/views/collaborations/_collaboration.html.erb
<div class='collaboration'>
  <span><%= collaboration.user.email %></span>
  <%= link_to 'X', collaboration, method: :delete, class: 'tiny secondary button', remote: true %>
</div>

app/views/collaborations/_collaborations.html.erb
<h3>Sharing list with</h3>
<div id='form-alert-container'></div>

<%= render partial: 'collaboration', collection: @collaborations %>

<%= form_for([@list, @collaboration], remote: true) do |f| %>
  <div class='row'>
    <div class='row collapse'>
      <div class="small-10 columns field">
        <%= f.email_field :user, placeholder: 'Email' %>
      </div>
      <div class='small-2 columns'>
        <%= f.submit "Share", class: 'button postfix' %>
      </div>
    </div>
  </div>
<% end %>

<div class='row clearfix'>
  <button id='form-cancel-button' class='button secondary right'>Done</button>
</div>

app/views/collaborations/index.js.erb
var $form = $('#collaboration-form');
$form.html("<%= j (render(partial: 'collaborations')) %>");
$(document).foundation();  // reapply foundation after adding content to modal

if (!$form.hasClass('open')) {
  $form.foundation('reveal', 'open');
}

$('#form-cancel-button').one('click', function(e){
  e.preventDefault();
  $form.foundation('reveal', 'close');
});

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box radius <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>List Share App</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <main role='main'>
      <nav class='top-bar' data-topbar role='navigation'>
        <ul class="title-area">
          <li class="name">
            <h1><a href="/">List Share App</a></h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
        </ul>

        <section class="top-bar-section">
          <ul class='right'>
            <% if user_signed_in? %>
              <li><%= link_to 'Profile', user_path(current_user) %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
            <% end %>
          </ul>
        </section>
      </nav>

      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/_collaborator.html.erb
<div class='list-user list-collaborator'>
  <%= collaborator.email %>
</div>

app/views/lists/_form.html.erb
<%= form_for(@list, remote: true) do |f| %>

  <div class="row field">
    <%= f.label :title do %>Title
      <%= f.text_field :title %>
    <% end %>
  </div>

  <div class="row field">
    <%= f.label :body do %>Text
      <%= f.text_area :body %>
    <% end %>
  </div>

  <div class='row clearfix'>
    <div class='right'>
      <button id='form-cancel-button' class='button secondary'>Cancel</button>
      <%= f.submit "Save", class: 'button' %>
    </div>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class='row list-row'>
  <div class='row'>
    <div class='small-12 columns list-title'>
      <strong><%= list.title %></strong>
    </div>
  </div>
  <div class='row'>
    <div class='small-12 columns list-body'><%= list.body %></div>
  </div>
  <% if list.user != current_user %>
    <div class='row'>
      <div class='small-12 columns'>
        <div class='right'>
          <span>shared by</span>
          <%= render partial: 'owner', object: list.user %>
        </div>
      </div>
    </div>
  <% elsif list.collaborators.any? %>
    <div class='row'>
      <div class='small-12 columns'>
        <div class='right'>
          <span>shared with</span>
          <%= render partial: 'collaborator', collection: list.collaborators %>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to '', list_path(list) %>
</div>

app/views/lists/_list_show.html.erb
<div class='row'>
  <h3><%= list_show.title %></h3>
</div>
<div class='row'>
  <p class='list-body'><%= list_show.body %></p>
</div>

app/views/lists/_owner.html.erb
<div class='list-user list-owner'>
  <%= owner.email %>
</div>

app/views/lists/create.js.erb
$('#list-form').foundation('reveal', 'close');
var list = $("<%= j (render @list) %>")
  .css({ display: 'none'});
$('#lists').prepend(list);
list.slideDown(350);

app/views/lists/edit.js.erb
$('#list-form').html("<%= j (render 'form') %>")
  .prepend($("<h3>Edit list</h3>"))
  .foundation('reveal', 'open');

$('#form-cancel-button').on('click', function(e){
  e.preventDefault();
  $('#list-form').foundation('reveal', 'close');
});

app/views/lists/index.html.erb
<div class='show-for-small-only'>
  <div class='small-12 columns'>
    <%= link_to 'New List', new_list_path, remote: true, class: 'left button' %>
  </div>
</div>

<div class='show-for-medium-up'>
  <div class='medium-3 large-2 columns'>
    <%= link_to 'New List', new_list_path, remote: true, class: 'button' %>
  </div>
</div>

<div class='small-12 medium-9 large-10 columns'>
  <div id='lists'>
    <%= render @lists %>
  </div>
</div>
<div id='list-form' class='reveal-modal' data-reveal data-options="animation: 'fade';"></div>

app/views/lists/new.js.erb
$('#list-form').html("<%= j (render 'form') %>")
  .prepend($("<h3>Create a new list</h3>"))
  .foundation('reveal', 'open');

$('#form-cancel-button').on('click', function(e){
  e.preventDefault();
  $('#list-form').foundation('reveal', 'close');
});

app/views/lists/show.html.erb
<div class='medium-6 medium-offset-3 small-12 columns'>

  <%= link_to 'Back', root_path, class: 'secondary button' %>
  <% if @list.user == current_user %>
    <%= link_to 'Delete', list_path(@list), class: 'alert button', method: :delete, data: { confirm: t('views.list.confirm_delete') } %>
    <%= link_to 'Sharing', list_collaborations_path(@list), remote: true, class: 'button' %>
  <% end %>
  <%= link_to 'Edit', edit_list_path(@list), remote: true, class: 'button' %>

  <div id='list-show'>
    <%= render partial: 'list_show', object: @list %>
  </div>

  <div id='list-form' class='reveal-modal' data-reveal data-options="animation: 'fade'"></div>
  <div id='collaboration-form' class='reveal-modal' data-reveal data-options="animation: 'fade'"></div>

</div>

app/views/lists/update.js.erb
$('#list-form').foundation('reveal', 'close');
var list = $("<%= j (render partial: 'list_show', object: @list) %>");
$('#list-show').html(list);

app/views/main/index.html.erb
<div class='medium-6 medium-offset-3 small-12 columns'>

  <div class='row'>
    <h3>What is this?</h3>
  </div>
  <div class='row'>
    <p>A simple app for creating and sharing lists</p>
  </div>

  <div class='row'>
    <h3>How can I start using it?</h3>
  </div>
  <div class='row'>
    <p>Either <%= link_to 'Sign Up', new_user_registration_path, class: 'button' %>
    or <%= link_to 'Sign In', new_user_session_path, class: 'button' %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class='medium-6 medium-offset-3 small-12 columns'>

  <div class='row'>
    <h3>Profile</h3>
  </div>

  <div class='row'>
    <p>Email: <%= @user.email %></p>
  </div>

</div>